faiss_db:
  collection_name: "document_portal"

embedding_model:
  google:
    model_name: "models/text-embedding-004"

  openai:
    model_name: "text-embedding-3-small"

llm:
  google:
    model_name: "gemini-2.0-flash"
    temperature: 1
    max_output_tokens: 2048

  openai:
    model_name: "gpt-4o"
    temperature: 1
    max_output_tokens: 2048
